use std::collections::{HashMap, HashSet};

use crate::parser::{Expr, parse};

mod generated;
mod parser;

fn find_ref(rule: &Expr, found: &mut HashSet<String>) {
    match rule {
        Expr::Marked(expr, _) => find_ref(&expr, found),
        Expr::Either(exprs) => exprs.iter().for_each(|e| find_ref(e, found)),
        Expr::Seq(exprs) => exprs.iter().for_each(|e| find_ref(e, found)),
        Expr::Literal(_, _) => {}
        Expr::Reference(reference) => {
            found.insert(to_enum(&reference));
        }
    }
}

fn find_lit(rule: &Expr, found: &mut HashSet<String>) {
    match rule {
        Expr::Marked(expr, _) => find_lit(&expr, found),
        Expr::Either(exprs) => exprs.iter().for_each(|e| find_lit(e, found)),
        Expr::Seq(exprs) => exprs.iter().for_each(|e| find_lit(e, found)),
        Expr::Reference(_) => {}
        Expr::Literal(_, lit) => {
            found.insert(lit.clone());
        }
    }
}

fn lit_map() -> HashMap<&'static str, &'static str> {
    [
        ("=", "EQ"),
        ("!", "BANG"),
        ("!=", "NEQ"),
        ("&&", "AMP2"),
        ("(", "L_PAREN"),
        (")", "R_PAREN"),
        ("*", "STAR"),
        ("+", "PLUS"),
        (",", "COMMA"),
        ("-", "MINUS"),
        (".", "STOP"),
        ("/", "SLASH"),
        (";", "SEMICOLON"),
        ("<", "L_ANGLE"),
        ("<=", "LTEQ"),
        (">", "R_ANGLE"),
        (">=", "GTEQ"),
        ("?", "QUESTION"),
        ("[", "L_BRACK"),
        ("]", "R_BRACK"),
        ("^", "CARET"),
        ("^^", "CARET2"),
        ("a", "TypePred"),
        ("{", "L_CURLY"),
        ("}", "R_CURLY"),
        ("|", "PIPE"),
        ("||", "PIPE2"),
    ]
    .into_iter()
    .collect()
}

fn to_enum(inp: &str) -> String {
    let mut out = String::new();

    let mut last_lowercase = false;
    for c in inp.chars() {
        if c.is_alphanumeric() {
            if c.is_lowercase() {
                last_lowercase = true;
            } else {
                if last_lowercase {
                    last_lowercase = false;
                    out.push('_')
                }
            }
            out.push(c);
        } else {
            out.push(c);
        }
    }

    out.to_uppercase()
}

fn main() {
    let output = parse(include_str!("../input.txt")).unwrap_or_default();

    let mut references = HashSet::new();
    let mut literals = HashSet::new();

    for r in &output {
        references.insert(to_enum(&r.name));

        find_ref(&r.expression, &mut references);
        find_lit(&r.expression, &mut literals);
    }

    let map = lit_map();
    let mut ref_list: Vec<_> = references.into_iter().collect();
    ref_list.sort_by_key(|x| x.to_lowercase());

    let mut lit_list: Vec<_> = Vec::new();
    let mut mac_list: Vec<(String, String)> = Vec::new();
    let mut from_kw: Vec<(String, String)> = Vec::new();

    for x in literals {
        let name = if let Some(r) = map.get(&x.as_str()) {
            r.to_string()
        } else {
            let name = format!(
                "{}_KW",
                x.to_uppercase().replace(" ", "_").replace("@", "AT_")
            );
            from_kw.push((x.to_lowercase(), name.clone()));
            name
        };
        let name = to_enum(&name);

        if "(){{}}[]".contains(&x) {
            mac_list.push((format!("'{}'", x), name.clone()));
        } else {
            mac_list.push((x, name.clone()));
        }
        lit_list.push(name);
    }

    lit_list.sort_by_key(|x| x.to_lowercase());

    println!(
        r#"
//! Generated by `cargo xtask codegen grammar`, do not edit by hand.
#![allow(bad_style, missing_docs, unreachable_pub)]
#[doc = r" The kind of syntax node, e.g. `IDENT`, `USE_KW`, or `STRUCT`."]
#[derive(Debug)]
#[repr(u16)]
pub enum SyntaxKind {{
    #[doc(hidden)]
    EOF,"#
    );
    for x in &lit_list {
        println!("    {},", x);
    }
    for x in &ref_list {
        println!("    {},", x);
    }
    println!(
        r#"    #[doc(hidden)]
    __LAST,
}}

use self::SyntaxKind::*;
impl SyntaxKind {{
    pub fn from_keyword(ident: &str) -> Option<SyntaxKind> {{
        let kw = match ident {{"#
    );

    for (k, v) in from_kw {
        println!("          \"{}\" => {},", k, v);
    }

    println!(
        r#"          _ => return None,
        }};

        Some(kw)
    }}
}}

#[doc = r" `T![]`"]
#[macro_export]
macro_rules ! T_ {{"#
    );
    for (k, v) in mac_list {
        println!("  [{}] => {{ crate::SyntaxKind::{} }};", k, v);
    }
    println!("}}")
}
